name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I am using the latest version or main branch
          required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run command `...`
        2. With input `...`
        3. See error...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Version or commit hash
      placeholder: "v0.1.0, commit hash, or 'main branch'"
    validations:
      required: true

  - type: input
    id: deno-version
    attributes:
      label: Deno Version
      description: Output of `deno --version`
      placeholder: "deno 1.40.0"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: command-output
    attributes:
      label: Command Output
      description: Relevant output from the transpiler
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
    validations:
      required: false
