name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Format check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno check src/**/*.ts

      - name: Run tests
        run: deno test --allow-read --allow-write --allow-env --allow-net tests/parser.test.ts tests/runtime.test.ts tests/transpiler.test.ts tests/type-checker.test.ts tests/unit/

      - name: Test coverage
        run: |
          deno test --allow-read --allow-write --allow-env --allow-net --coverage=.output/coverage tests/parser.test.ts tests/runtime.test.ts tests/transpiler.test.ts tests/type-checker.test.ts tests/unit/
          deno coverage .output/coverage --lcov --output=.output/coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./.output/coverage.lcov
          fail_ci_if_error: false

      - name: Verify JSR package
        run: deno publish --dry-run
